site_name: HuSpaCy
site_description: Industrial-strength Hungarian natural language processing
site_author: György Orosz, SzegedAI
site_url: https://huspacy.github.io
repo_url: https://github.com/huspacy/huspacy
repo_name: huspacy/huspacy
nav:
  - Home: index.md
  - Docs:
      - Installation: huspacy/installation.md
      - Quickstart: huspacy/quickstart.md
      - Integrating with R: huspacy/usage_in_r.md
      - Reference:
          - huspacy: reference/huspacy/__init__.md
          - components:
              - edit_tree_lemmatizer.py: reference/huspacy/components/edit_tree_lemmatizer.md
              - hun_sentencizer.py: reference/huspacy/components/hun_sentencizer.md
              - lookup_lemmatizer.py: reference/huspacy/components/lookup_lemmatizer.md
              - lemma_postprocessing.py: reference/huspacy/components/lemma_postprocessing.md
      - Changelog: huspacy/changelog.md
  - Models:
      - Introduction: models/index.md
      - Changelogs:
          - hu_core_news_md: models/changelog_md.md
          - hu_core_news_lg: models/changelog_lg.md
          - hu_core_news_trf: models/changelog_trf.md
  - Application examples:
      - Anonymizer: examples/anonymizer.md
      - Entity linking: examples/dbpedia.md
      - Keyphrase extraction: examples/keyphrase.md
      - Relation extraction: examples/relation.md
  - Demo: https://huggingface.co/spaces/huspacy/demo

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/code-tags
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - navigation.tabs
#    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: white
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - huspacy

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            show_source: False
            show_root_toc_entry: False
#            show_root_members_full_path: True
            docstring_section_style: table
            line_length: 80
            show_if_no_docstring: True
            show_signature_annotations: False
            separate_signature: True
            filters: ["!^_"]
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


#extra:
#  analytics:
#    provider: google
#    property: G-XXXXXXXXXX