command:
- spacy
- train
- configs/parser.cfg
- --code
- ../huspacy/huspacy/components/edit_tree_lemmatizer.py
- --gpu-id
- ${envvar:GPU}
- --training.logger.project_name
- parser_finetune
- --paths.vectors
- models/floret.vectors
- --paths.train
- data/processed/UD_Hungarian-Szeged/train.spacy
- --paths.dev
- data/processed/UD_Hungarian-Szeged/dev.spacy
- --paths.tagger_model
- models/hu_core_news_md-tagger-3.6.0/model-best
- ${args}
method: bayes
metric:
  name: score
  goal: maximize
parameters:
  training.optimizer.learn_rate:
    values:
    - 0.01
    - 0.006
    - 0.003
    - 0.001
    - 0.0005
    - 0.0001
    - 0.00001
  training.optimizer.grad_clip:
    values:
    - 1.0
    - 5.0
  training.optimizer.L2:
    values:
    - 1e-2
    - 1e-3
    - 1e-4
    - 1e-5
    - 1e-6
  training.optimizer.use_averages:
    values:
    - true
    - false
