project: spacy_trf_tagger
command:
- spacy
- train
- ./configs/tagger.cfg
- --code
- ../huspacy/huspacy/components/edit_tree_lemmatizer.py
- --gpu-id
- ${envvar:GPU}
- --paths.train
- data/processed/SzegedCorpus/train.spacy
- --paths.dev
- data/processed/UD_Hungarian-Szeged/dev.spacy
- ${args}
method: bayes
metric:
  name: score
  goal: maximize
parameters:
  training.dropout:
    values:
    - 0.1
    - 0.2
    - 0.3
  training.optimizer.learn_rate.initial_rate:
    values:
    - 1e-3
    - 1e-4
    - 5e-5
    - 1e-5
  training.optimizer.L2:
    values:
      - 1e-1
      - 1e-2
      - 1e-3
  training.optimizer.use_averages:
    values:
      - true
      - false
