project: spacy_trf_parser
command:
- python
- -m
- spacy
- train
- ./configs/parser.cfg
- --output
- ../transformer_models/sweep_parser
- --gpu-id
- 0
- ${args}
method: grid
parameters:
  components.parser.model.extra_state_tokens:
    values:
      - true
      - false
  components.parser.model.hidden_width:
    values:
      - 64
      - 128
      - 256
  components.parser.model.maxout_pieces:
    values:
      - 1
      - 2
      - 3
  nlp.lang:
    values:
    - hu
  paths.dev:
    values:
      - ../data/processed/UD_Hungarian_Szeged/dev.spacy
  paths.train:
    values:
      - ../data/processed/UD_Hungarian_Szeged/train.spacy
  training.dropout:
    values:
    - 0.1
    - 0.2
    - 0.3
    - 0.5
  training.optimizer.L2:
    values:
    - 0.1
    - 0.01
    - 0.001