name: Docs

on:
  push:
    branches:
      - docs

jobs:
  publish_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout huspacy
      uses: actions/checkout@v3
      with:
        path: repo

    - name: Checkout huspacy/huspacy.github.io
      uses: actions/checkout@v3
      with:
        repository: huspacy/huspacy.github.io
        path: huspacy.github.io
        ssh-key: ${{ secrets.GH_PAGES_GIT_KEY }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry

    - name: Install Python dependencies
      run: |
        cd repo/huspacy
        poetry install

    - name: Generate docs
      run: |
        cd repo/huspacy
        source ./.venv/bin/activate
        
        cd ../../huspacy.github.io
        git checkout gh-pages
        git pull --rebase
        
        cd ../repo
        mkdocs build -d --clean -d ../huspacy.github.io
        
        cd ../huspacy.github.io
        git config user.email "gyorgy+bot@orosz.link"
        git config user.name "HuSpaCy Bot"
        git add .
        git commit -m "Updated website to reflect changes at https://github.com/huspacy/huspacy/commit/$GITHUB_SHA"
        git push origin gh-pages