name: Docs

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout huspacy
      uses: actions/checkout@v3
      with:
        path: repo

    - name: Checkout huspacy/huspacy.github.io
      uses: actions/checkout@v3
      with:
        repository: huspacy/huspacy.github.io
        path: huspacy.github.io
        ssh-key: ${{ secrets.GH_PAGES_GIT_KEY }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: 1.5.1

    - uses: actions/cache@v2
      with:
        path: huspacy/.venv
        key: ${{ runner.os }}-py${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install Python dependencies
      run: |
        cd repo/huspacy
        poetry install --with docs --with dev --all-extras
        poetry run pip install https://github.com/nytud/emmorphpy/releases/download/v1.1.0/emmorphpy-1.1.0-py3-none-any.whl
        poetry run pip install https://github.com/vadno/emmorph2ud2/releases/download/v1.0.1/emmorph2ud2-1.0.1-py3-none-any.whl

    - name: Install hfst
      run: sudo apt-get install -y hfst

    - name: Test citation file
      run: |
        cd repo/huspacy
        poetry run cffconvert -i ../CITATION.cff --validate

    - name: Test code snippets in the documentation
      run: |
        cd repo/huspacy
        poetry run pytest --codeblocks --verbosity=3 ./README.md  ../docs/huspacy/*.md ../docs/recipes/*.md

    - name: Generate docs
      run: |
        cd repo/huspacy
        source ./.venv/bin/activate
        
        cd ../../huspacy.github.io
        git checkout gh-pages
        git pull --rebase
        
        cd ../repo
        mkdocs build -d --clean -d ../huspacy.github.io

    - name: Publish
      if: github.ref == 'refs/heads/master' #|| github.ref == 'refs/heads/develop'
      run: |
        cd huspacy.github.io
        git config user.email "gyorgy+bot@orosz.link"
        git config user.name "HuSpaCy Bot"
        git add .
        git commit -m "Updated website to reflect changes at https://github.com/huspacy/huspacy/commit/$GITHUB_SHA"
        git push origin gh-pages
