name: Test models

on:
  push:
    branches:
      - develop

jobs:
  test_models:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: huspacy
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        model-name: ["hu_core_news_md", "hu_core_news_lg", "hu_core_news_trf"]

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the package
        run: |
          pip install -U pip 
          pip install spacy_conll typer
          pip install https://huggingface.co/huspacy/${{ matrix.model-name }}/resolve/main/${{ matrix.model-name }}-any-py3-none-any.whl

      - name: Smoke test
        run: |
          python scripts/smoke_test.py